### ISSUE TITLE
Is blastn tabular format possible ?

### ISSUE THREAD

**Issue by colindaven** [masayano/CLAST#2]
One feature request - is it possible to generate an blastn tabular format from CLAST output ? It is very similar indeed, but I wonder if you've looked into this.

Thanks!
Colin

**Comment by masayano** [comment]
Hi,

Thank you for your request. But I'm sorry because it is impossible at least for this major version of CLAST. In order to save GPU memory during alignments, CLAST discards number of gaps and mismatches.

However, I want to make CLAST possible generate blastn tabular format at next major update because it is much more convenient (especially for beginners).

Always thank you!
Masahiro

**Comment by colindaven** [comment]
Great, blastn format would be fantastic if possible, not because it's convenient for beginners, but because it is in at least some way a type of standard format. Standard formats, for example, GFF3, GTF or SAM, are critically important for bioinformatics because follow up programs can build on them. 

I was considering using CLAST output for a tool called proteinortho, which uses blastn output.

Thanks for your efforts, and I appreciate this may not be convenient/desirable/possible, but it was interesting to ask anyway.
Colin
